# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Howtank Widget Sample' do
  use_frameworks!

  # Pods for Howtank Widget Sample
  #pod 'HowtankWidgetSwift', :path => '../HowtankWidgetSwift'
  pod 'HowtankWidgetSwift', '2.3.0'

end
